import json
import re
from typing import Any

from app.config import MAX_CONVERSATION_TURNS
from app.llm.prompts import SYSTEM_PROMPT
from app.llm.conversation_memory import ConversationReminder
from app.llm.conversation_state import ConversationState
from app.llm.conversation_topic_detector import TopicDetector
from app.llm.conversation_state_summarizer import ConversationStateSummarizer
from app.llm.llm_api_client import LLMClient
from app.logging import get_logger


class BaseConversationPipeline:
    """Base class for conversation pipelines."""

    def __init__(self) -> None:
        """Initialize the conversation processing pipeline"""
        self.llm = LLMClient()

        self.state = ConversationState()
        self.topic_detector = TopicDetector()
        self.summarizer = ConversationStateSummarizer(llm=self.llm)

        self.logger = get_logger(self.__class__.__name__)

    def prepare_prompts_to_llm(
        self,
        user_input_text: str,
        chat_memory: ConversationReminder,
        user_profile: dict[str, Any] | None = None,
    ) -> list[dict[str, str]]:
        """Build the final prompt to the Model, preparing previous context if applicable

        :user_input_text: User input text
        :chat_memory: ConversationReminder instance containing the conversation history
        :user_profile: Optional dictionary containing user profile information (e.g., name, preferences)
        :returns: A list of dicts where each dict is a prompt to the Model
        """
        context_block = ""
        if user_profile:
            context_block = (
                "User General Profile:\n"
                f"Name: {user_profile.get('name', '')}\n"
                f"Preferred languages: {user_profile.get('preferred_languages', '')}\n"
                f"Interests: {user_profile.get('interests', '')}\n"
                f"Conversation style: {user_profile.get('conversation_style', '')}\n"
            )

        if not self.state.is_empty():
            context_block += (
                "Current Conversation Context:\n"
                f"Topic: {self.state.topic}\n"
                f"Summary: {self.state.summary}\n"
                f"User tone: {self.state.tone}\n"
            )

        prompts = [{"role": "system", "content": SYSTEM_PROMPT}]

        if context_block:
            prompts.append(
                {
                    "role": "system",
                    "content": f"- 'Conversation context' (use as guidance, not strict rules):\n{context_block}",
                }
            )

        prompts.extend(
            [
                *chat_memory.get_messages(),
                {"role": "user", "content": user_input_text},
            ]
        )
        return prompts

    def _set_periodicity(self) -> int:
        """Set the periodicity for updating the user profile. Ensuring always a even number."""
        periodicity = round(MAX_CONVERSATION_TURNS / 2)
        if periodicity % 2 != 0:
            periodicity += 1
        return periodicity

    async def update_conversation_context(self, language: str, user_input_text: str, model_output_text: str) -> None:
        """Update the conversation state based on the latest interaction

        :language: Language used by user
        :user_input_text: Text from user input
        :model_output_text: Text generated by the language model
        """
        raw_state = await self.summarizer.get_updated_state(
            previous_summary=self.state.summary,
            user_text=user_input_text,
            assistant_text=model_output_text,
            language=language,
        )

        try:
            cleaned = re.sub(r"^```json\s*|```$", "", raw_state.strip(), flags=re.MULTILINE)
            parsed = json.loads(cleaned)
        except json.JSONDecodeError:
            self.logger.error(f"Failed to parse conversation state to JSON: {raw_state}")
            parsed = {}

        self.state.topic = parsed.get("topic")
        self.state.summary = parsed.get("summary")
        self.state.tone = parsed.get("tone")
        self.state.language = language

    async def update_user_profile(
        self, chat_memory: ConversationReminder, user_profile: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        """Update the user profile based on the latest conversation history.
        Only updates if the number of iteractions is a multiple of MAX_CONVERSATION_TURNS.

        :chat_memory: ConversationReminder instance containing the conversation history
        :user_profile: Optional dictionary containing previous user profile information
        :returns: Updated user profile as a dictionary
        """
        parsed_profile = {}
        last_messages = chat_memory.get_messages()
        is_initial_turn = len(last_messages) == 2
        if is_initial_turn or len(last_messages) % self._set_periodicity() == 0:
            raw_user_profile = await self.summarizer.get_updated_user_profile(
                previous_user_profile=user_profile, last_messages=last_messages
            )
            try:
                parsed_profile = json.loads(raw_user_profile)
            except json.JSONDecodeError:
                self.logger.error(f"Failed to parse user profile to JSON: {raw_user_profile}")
                parsed_profile = {}
        else:
            self.logger.debug(f"Skipping user profile update. Total messages: {len(last_messages)}.\n")

        return parsed_profile

    async def process_conversation(self) -> dict[str, Any]:
        """Orchestrates the full conversation flow.
        Must return at least the following keys in the result dict:
            - user_input_text: The text from user input
            - model_output_text: The text generated by the language model
        """
        raise NotImplementedError("Subclasses must implement this method")
