import json
from pathlib import Path

from app.audio.formats import to_wav
from app.llm.prompts import SYSTEM_PROMPT
from app.llm.conversation_memory import ConversationMemory
from app.llm.conversation_state import ConversationState
from app.llm.conversation_topic_detector import TopicDetector
from app.llm.conversation_state_summarizer import ConversationStateSummarizer
from app.llm.ollama_client import OllamaClient
from app.logging import get_logger
from app.stt.whisper_engine import WhisperEngine
from app.tts.edge_tts_engine import EdgeTTSEngine
from app.tts.voices import DEFAULT_VOICE, VOICE_BY_LANGUAGE
from app.utils import run_in_thread


class AudioConversationPipeline:
    """
    This pipeline orchestrates the full audio-to-audio flow:
    speech-to-text (Whisper), text generation (Ollama),
    and text-to-speech (Edge TTS).
    """

    def __init__(self) -> None:
        """Initialize the voice processing pipeline"""
        self.stt = WhisperEngine()
        self.llm = OllamaClient()

        self.memory = ConversationMemory()
        self.state = ConversationState()
        self.topic_detector = TopicDetector()
        self.summarizer = ConversationStateSummarizer(llm=self.llm)

        self.logger = get_logger(self.__class__.__name__)

    async def transcribe_user_audio(self, audio_path: Path) -> dict[str, str]:
        """Run the user audio through the Speech-To-Text pipeline, ensuring WAV format.

        :audio_path: Path to the input audio file (sent by the user)
        :returns: Dict containing both language and the transcribed text.
        """
        if audio_path.suffix.lower() != ".wav":
            wav_path = audio_path.with_suffix(".wav")
            await run_in_thread(to_wav, audio_path, wav_path)
        else:
            wav_path = audio_path

        stt_result = await run_in_thread(self.stt.transcribe, str(wav_path))
        language = stt_result["language"]
        user_input_text = stt_result["text"]
        return {"language": language, "user_input_text": user_input_text}

    def prepare_prompts_to_llm(self, language: str, user_input_text: str) -> list[dict[str, str]]:
        """Build the final prompt to the Model, preparing previous context if applicable

        :language: Language used by user
        :user_input_text: Transcribed user audio
        :returns: A list of dicts where each dict is a prompt to the Model
        """
        context_block = ""
        if not self.state.is_empty():
            context_block = f"""
                Conversation context:
                Topic: {self.state.topic}
                Summary: {self.state.summary}
                User tone: {self.state.tone}
                """

        if self.state.language and language != self.state.language:
            # If user changes language, avoids to mix multilanguages contexts
            self.state.clear()
            self.memory.clear()

        prompts = [
            {"role": "system", "content": SYSTEM_PROMPT + context_block},
            *self.memory.get_messages(),
            {"role": "user", "content": user_input_text},
        ]

        return prompts

    async def update_conversation_context(self, language: str, user_input_text: str, model_output_text: str) -> None:
        """Update the conversation state based on the latest interaction

        :language: Language used by user
        :user_input_text: Transcribed user audio
        :model_output_text: Text generated by the language model
        """
        raw_state = await self.summarizer.update_state(
            previous_summary=self.state.summary,
            user_text=user_input_text,
            assistant_text=model_output_text,
            language=language,
        )

        try:
            parsed = json.loads(raw_state)
        except json.JSONDecodeError:
            parsed = {}

        self.state.topic = parsed.get("topic")
        self.state.summary = parsed.get("summary")
        self.state.tone = parsed.get("tone")
        self.state.language = language

    async def synthesize_audio_output(self, language: str, model_output_text: str, output_audio_path: Path) -> Path:
        """Synthesize the model output text into speech audio using Edge TTS

        :language: Language used for synthesis
        :model_output_text: Text to be synthesized
        :output_audio_path: Path to save the synthesized audio
        :returns: Path to the synthesized audio file
        """
        supported_languages = set(VOICE_BY_LANGUAGE.keys())
        if language not in supported_languages:
            voice = DEFAULT_VOICE
            self.logger.warning(f"Language {language} not supported. Using fallback voice {DEFAULT_VOICE} ")
        else:
            voice = VOICE_BY_LANGUAGE.get(language)

        tts = EdgeTTSEngine(voice=voice)
        output_path = await tts._synthesize_speech_from_text(model_output_text, output_audio_path)
        return output_path

    async def process_audio_conversation(self, user_input_audio_path: Path, output_audio_path: Path):
        """Orchestrates the full audio-to-audio conversation flow.

        The method executes the following steps:
        1. Transcribes the input audio to text using Whisper (STT)
        2. Detects if the topic has changed and resets context if needed
        3. Prepares prompts including conversation history for the LLM
        4. Sends prompts to the Ollama LLM and retrieves the generated response
        5. Updates the conversation context and state
        6. Synthesizes the LLM response into speech audio using Edge TTS

        :user_input_audio_path: Path to the input audio file (WAV format expected)
        :output_audio_path: Path where the generated output audio will be saved
        :returns: A dictionary containing the transcription, response,
            detected language, and output audio path
        """
        # User input preparing (STT)
        stt_result = await self.transcribe_user_audio(user_input_audio_path)
        language = stt_result["language"]
        user_input_text = stt_result["user_input_text"]
        self.logger.info(f"[STT] Received prompt:\n\t({language}) {user_input_text}")

        # Topic detection
        if self.topic_detector.is_new_topic(self.state.summary, user_input_text):
            self.logger.info("Topic change detected. Resetting conversation state.")
            self.state.clear()
            self.memory.clear()

        # Prompt construction
        prompts = self.prepare_prompts_to_llm(language, user_input_text)
        for prompt in prompts:
            self.logger.debug(f"\nEnqueued prompt: {prompt}")

        # LLM output preparing
        model_output_text = await self.llm.chat(prompts)
        self.logger.info(f"[LLM] Response:\n\t{model_output_text}")
        self.memory.add_user_message(user_input_text)
        self.memory.add_assistant_message(model_output_text)

        # Conversation context update
        await self.update_conversation_context(language, user_input_text, model_output_text)
        self.logger.info("Conversation context was updated succesfully.")

        # Output voice audio preparing (TTS)
        synthesized_audio_path = await self.synthesize_audio_output(language, model_output_text, output_audio_path)

        return {
            "language": language,
            "user_input_text": user_input_text,
            "model_output_text": model_output_text,
            "synthesized_audio_path": synthesized_audio_path,
        }
